/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoa3facul.VIEW;

/**
 *
 * @author paulo
 */
public class Esquecisenha extends javax.swing.JFrame {

    /**
     * Creates new form Esquecisenha
     */
    public Esquecisenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelDigiteRG = new javax.swing.JLabel();
        labelDigiteCPF = new javax.swing.JLabel();
        labelSeuSexo = new javax.swing.JLabel();
        labelSuaIdade = new javax.swing.JLabel();
        labelPalavraChave = new javax.swing.JLabel();
        textFieldRG = new javax.swing.JTextField();
        textFieldSexo = new javax.swing.JTextField();
        textFieldIdade = new javax.swing.JTextField();
        textFieldPalavraChave = new javax.swing.JTextField();
        textFieldCPF = new javax.swing.JTextField();
        buttonVoltar = new javax.swing.JButton();
        buttonProximo = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(222, 222, 222));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        labelDigiteRG.setBackground(new java.awt.Color(222, 222, 222));
        labelDigiteRG.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        labelDigiteRG.setForeground(new java.awt.Color(0, 0, 0));
        labelDigiteRG.setText("Digite seu RG");

        labelDigiteCPF.setBackground(new java.awt.Color(222, 222, 222));
        labelDigiteCPF.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        labelDigiteCPF.setForeground(new java.awt.Color(0, 0, 0));
        labelDigiteCPF.setText("Digite seu CPF");

        labelSeuSexo.setBackground(new java.awt.Color(222, 222, 222));
        labelSeuSexo.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        labelSeuSexo.setForeground(new java.awt.Color(0, 0, 0));
        labelSeuSexo.setText("Seu Sexo");

        labelSuaIdade.setBackground(new java.awt.Color(222, 222, 222));
        labelSuaIdade.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        labelSuaIdade.setForeground(new java.awt.Color(0, 0, 0));
        labelSuaIdade.setText("Sua idade");

        labelPalavraChave.setBackground(new java.awt.Color(222, 222, 222));
        labelPalavraChave.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        labelPalavraChave.setForeground(new java.awt.Color(0, 0, 0));
        labelPalavraChave.setText("Palavra chave");

        textFieldRG.setBackground(new java.awt.Color(222, 222, 222));
        textFieldRG.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textFieldRG.setForeground(new java.awt.Color(0, 0, 0));
        textFieldRG.setText("jTextField1");

        textFieldSexo.setBackground(new java.awt.Color(222, 222, 222));
        textFieldSexo.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textFieldSexo.setForeground(new java.awt.Color(0, 0, 0));
        textFieldSexo.setText("jTextField1");

        textFieldIdade.setBackground(new java.awt.Color(222, 222, 222));
        textFieldIdade.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textFieldIdade.setForeground(new java.awt.Color(0, 0, 0));
        textFieldIdade.setText("jTextField1");

        textFieldPalavraChave.setBackground(new java.awt.Color(222, 222, 222));
        textFieldPalavraChave.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textFieldPalavraChave.setForeground(new java.awt.Color(0, 0, 0));
        textFieldPalavraChave.setText("jTextField1");

        textFieldCPF.setBackground(new java.awt.Color(222, 222, 222));
        textFieldCPF.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        textFieldCPF.setForeground(new java.awt.Color(0, 0, 0));
        textFieldCPF.setText("jTextField1");

        buttonVoltar.setBackground(new java.awt.Color(222, 222, 222));
        buttonVoltar.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        buttonVoltar.setForeground(new java.awt.Color(0, 0, 0));
        buttonVoltar.setText("Voltar");
        buttonVoltar.setPreferredSize(new java.awt.Dimension(76, 27));
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        buttonProximo.setBackground(new java.awt.Color(222, 222, 222));
        buttonProximo.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        buttonProximo.setForeground(new java.awt.Color(0, 0, 0));
        buttonProximo.setText("Proximo");
        buttonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelDigiteRG, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldPalavraChave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldIdade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSeuSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDigiteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSuaIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDigiteRG)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDigiteCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSeuSexo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSuaIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPalavraChave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonProximo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        TelaGrafica tela = new TelaGrafica();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    private void buttonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Esquecisenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Esquecisenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Esquecisenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Esquecisenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Esquecisenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProximo;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDigiteCPF;
    private javax.swing.JLabel labelDigiteRG;
    private javax.swing.JLabel labelPalavraChave;
    private javax.swing.JLabel labelSeuSexo;
    private javax.swing.JLabel labelSuaIdade;
    private javax.swing.JTextField textFieldCPF;
    private javax.swing.JTextField textFieldIdade;
    private javax.swing.JTextField textFieldPalavraChave;
    private javax.swing.JTextField textFieldRG;
    private javax.swing.JTextField textFieldSexo;
    // End of variables declaration//GEN-END:variables
}
