/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoa3facul.VIEW;

/**
 *
 * @author paulo
 */
public class MinhaInformacoes extends javax.swing.JFrame {

    /**
     * Creates new form MinhaInformacoes
     */
    public MinhaInformacoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScroolPane = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelCPF = new javax.swing.JLabel();
        labelRG = new javax.swing.JLabel();
        lavelEmail = new javax.swing.JLabel();
        labelSexo = new javax.swing.JLabel();
        labelIdade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaNome = new javax.swing.JList<>();
        buttonVoltar = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        listaNome1 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        listaNome2 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        listaNome3 = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        listaNome4 = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        listaNome5 = new javax.swing.JList<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScroolPane.setBackground(new java.awt.Color(222, 222, 222));
        jScroolPane.setForeground(new java.awt.Color(0, 0, 0));

        labelNome.setBackground(new java.awt.Color(222, 222, 222));
        labelNome.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        labelNome.setForeground(new java.awt.Color(0, 0, 0));
        labelNome.setText("Meu nome");

        labelCPF.setBackground(new java.awt.Color(222, 222, 222));
        labelCPF.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        labelCPF.setForeground(new java.awt.Color(0, 0, 0));
        labelCPF.setText("CPF");

        labelRG.setBackground(new java.awt.Color(222, 222, 222));
        labelRG.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        labelRG.setForeground(new java.awt.Color(0, 0, 0));
        labelRG.setText("RG");

        lavelEmail.setBackground(new java.awt.Color(222, 222, 222));
        lavelEmail.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lavelEmail.setForeground(new java.awt.Color(0, 0, 0));
        lavelEmail.setText("Email");

        labelSexo.setBackground(new java.awt.Color(222, 222, 222));
        labelSexo.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        labelSexo.setForeground(new java.awt.Color(0, 0, 0));
        labelSexo.setText("Sexo");

        labelIdade.setBackground(new java.awt.Color(222, 222, 222));
        labelIdade.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        labelIdade.setForeground(new java.awt.Color(0, 0, 0));
        labelIdade.setText("Idade");

        listaNome.setBackground(new java.awt.Color(222, 222, 222));
        listaNome.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        listaNome.setForeground(new java.awt.Color(0, 0, 0));
        listaNome.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaNome);

        buttonVoltar.setBackground(new java.awt.Color(222, 222, 222));
        buttonVoltar.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        buttonVoltar.setForeground(new java.awt.Color(0, 0, 0));
        buttonVoltar.setText("Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarActionPerformed(evt);
            }
        });

        listaNome1.setBackground(new java.awt.Color(222, 222, 222));
        listaNome1.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        listaNome1.setForeground(new java.awt.Color(0, 0, 0));
        listaNome1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(listaNome1);

        listaNome2.setBackground(new java.awt.Color(222, 222, 222));
        listaNome2.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        listaNome2.setForeground(new java.awt.Color(0, 0, 0));
        listaNome2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(listaNome2);

        listaNome3.setBackground(new java.awt.Color(222, 222, 222));
        listaNome3.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        listaNome3.setForeground(new java.awt.Color(0, 0, 0));
        listaNome3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(listaNome3);

        listaNome4.setBackground(new java.awt.Color(222, 222, 222));
        listaNome4.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        listaNome4.setForeground(new java.awt.Color(0, 0, 0));
        listaNome4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(listaNome4);

        listaNome5.setBackground(new java.awt.Color(222, 222, 222));
        listaNome5.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        listaNome5.setForeground(new java.awt.Color(0, 0, 0));
        listaNome5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane11.setViewportView(listaNome5);

        javax.swing.GroupLayout jScroolPaneLayout = new javax.swing.GroupLayout(jScroolPane);
        jScroolPane.setLayout(jScroolPaneLayout);
        jScroolPaneLayout.setHorizontalGroup(
            jScroolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jScroolPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jScroolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane11)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jScroolPaneLayout.createSequentialGroup()
                        .addGroup(jScroolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lavelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jScroolPaneLayout.createSequentialGroup()
                        .addComponent(labelNome, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(buttonVoltar)))
                .addContainerGap())
        );
        jScroolPaneLayout.setVerticalGroup(
            jScroolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jScroolPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jScroolPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(buttonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lavelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSexo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScroolPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScroolPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarActionPerformed
        telamenu menu = new telamenu();
        menu.setVisible(true);
        

        dispose();
    }//GEN-LAST:event_buttonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinhaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinhaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinhaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinhaInformacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinhaInformacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel jScroolPane;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelIdade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRG;
    private javax.swing.JLabel labelSexo;
    private javax.swing.JLabel lavelEmail;
    private javax.swing.JList<String> listaNome;
    private javax.swing.JList<String> listaNome1;
    private javax.swing.JList<String> listaNome2;
    private javax.swing.JList<String> listaNome3;
    private javax.swing.JList<String> listaNome4;
    private javax.swing.JList<String> listaNome5;
    // End of variables declaration//GEN-END:variables
}
